"""empty message

Revision ID: 47bf80a8ad8a
Revises: 
Create Date: 2021-03-05 12:27:39.988477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bf80a8ad8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'actor', ['name'])
    op.create_unique_constraint(None, 'movie', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_constraint(None, 'actor', type_='unique')
    # ### end Alembic commands ###
